#!/bin/bash
# TC4: Reconnect — rút camera → cắm lại → stream resume
# Requires: c270_app đang chạy VỚI hotplug enabled
echo "═══ TC4: Reconnect Test ═══"
echo ""
echo "Test này cần thực hiện THỦ CÔNG:"
echo ""
echo "Bước 1: Chạy driver với hotplug:"
echo "  sudo bash unbind_c270.sh"
echo "  sudo ./build/c270_app"
echo ""
echo "Bước 2: RÚT camera USB ra"
echo "  → Console phải hiện: [HOTPLUG] Camera unplugged!"
echo "  → Console phải hiện: [MAIN] Stream paused"
echo ""
echo "Bước 3: CẮM camera USB lại"
echo "  → Console phải hiện: [HOTPLUG] Camera detected"
echo "  → Console phải hiện: [MAIN] Stream resumed after reconnect"
echo ""
echo "Bước 4: Verify video hiển thị lại trên SDL window"
echo ""
echo "── Checklist ──"
echo "  [ ] Camera unplugged detected"
echo "  [ ] No crash khi rút camera"
echo "  [ ] Camera reconnected detected"
echo "  [ ] Stream resumed"
echo "  [ ] Video hiển thị lại (SDL)"
echo "  [ ] RTSP stream vẫn accessible"
echo ""
echo "═══ TC4: Manual Test ═══"
